export const data = [
    {
      id: 1,
      name: "Conversor de Moedas Fetch Api",
      gif: "./src/assets/gifs/Currency_Converter_Fetch_Api.gif",
      link: "https://currency-converter-using-a-fetch-api.vercel.app/",
      gitHub:
        "https://github.com/Danielsilverio81/currency_converter_using_a_fetch_api",
      imageDefault: "./src/assets/images/project_preview_1.png",
    },
    {
      id: 2,
      name: "Site de Clinica Medica Fictício",
      gif: "./src/assets/gifs/medical_clinic_website.gif",
      link: "https://responsive-website-beta.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/Responsive_website_project",
      imageDefault: "./src/assets/images/project_preview_2.png",
    },
    {
      id: 3,
      name: "Landing Page Workit Desafio FrontEnd Mentor",
      gif: "./src/assets/gifs/Landing_page_copies_challenge_Front_End_Mentor.gif",
      link: "https://front-end-mentor-landing-page-workit-challenge.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/FrontEnd_Mentor_Landing_page-workit_challenge",
      imageDefault: "./src/assets/images/project_preview_3.png",
    },
    {
      id: 4,
      name: "Landing Page Equalizer Desafio FrontEnd Mentor",
      gif: "./src/assets/gifs/Landing_page_Equalizer_Challenge_Front_End_Mentor.gif",
      link: "https://equalizerlandingpage.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/equalizer-landingpage-project",
      imageDefault: "./src/assets/images/project_preview_4.png",
    },
    {
      id: 5,
      name: "Flappy Bird Copia em Javascript puro",
      gif: "./src/assets/gifs/flappy_bird_game_in_js.gif",
      link: "https://flappy-copy-in-js.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/Flappy-B_in_JS",
      imageDefault: "./src/assets/images/project_preview_5.png",
    },
    {
      id: 6,
      name: "Agencia de Viagens Formulário",
      gif: "./src/assets/gifs/Travel_agency_form.gif",
      link: "https://travel-agency-form-q60gk6d23-danielsilverio81.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/Travel_agency_form",
      imageDefault: "./src/assets/images/project_preview_6.png",
    },
    {
      id: 7,
      name: "Calculadora de IMC",
      gif: "./src/assets/gifs/imc_calc.gif",
      link: "https://imc-calculator-in-pure-javascript-c7ks2wfpm-danielsilverio81.vercel.app/",
      gitHub: "https://github.com/Danielsilverio81/IMC_calculator_in_pure_javascript",
      imageDefault: "./src/assets/images/project_preview_7.png",
    },
    {
      id: 8,
      name: "SpaceX copia",
      gif: "./src/assets/gifs/spaceX_WebSite_copy.gif",
      link: "https://my-spacex-website-version.vercel.app/index.html",
      gitHub: "https://github.com/Danielsilverio81/My_spacex_website_version_in_bootstrap_and_sass",
      imageDefault: "./src/assets/images/project_preview_8.png",
    },
  ];